/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.raven.datechooser.EventDateChooser;
import com.raven.datechooser.SelectedAction;
import com.raven.datechooser.SelectedDate;
import controller.RegisterCtl;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import model.Person;

/**
 *
 * @author Admin
 */
public class AccounInformationView extends javax.swing.JFrame {

    /**
     * Creates new form AccounInformationView
     */
    RegisterCtl rg = RegisterCtl.getinstance();
    public AccounInformationView() {
        initComponents();
        dateChooser = new com.raven.datechooser.DateChooser();
        dateChooser.setTextRefernce(txtDate1);
        this.setSize(1215, 730);
        this.setTitle("Register");
        this.setLocationRelativeTo(null);
         ImageIcon icon = new ImageIcon(getClass().getResource("/image/logoapp.png"));
        Image image = icon.getImage();
        setIconImage(image);
        setBtn();
        
          dateChooser.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser.hidePopup();
                }
            }
        });
    }
    
    public boolean checkBlankField() // Kiểm tra các trường nhập có rỗng hay không?
    {
        return txtName.getText().trim().equals("") || txtAddress.getText().trim().equals("") || txtTelephone.getText().trim().equals("")
                || txtEmail.getText().trim().equals(""); 
    }
    
    public boolean checkEmailRegex(String str) {
        Pattern regex = Pattern.compile("\\b[\\w.%-]+@[-.\\w]+\\.[A-Za-z]{2,4}\\b");
        Matcher m = regex.matcher(str);
        if (m.find()) {
            return true;
        }
        return false;
    }
    
    public boolean checkPhone(String str){
        // Bieu thuc chinh quy mo ta dinh dang so dien thoai
        String reg = "^(0|\\+84)(\\s|\\.)?((3[2-9])|(5[689])|(7[06-9])|(8[1-689])|(9[0-46-9]))(\\d)(\\s|\\.)?(\\d{3})(\\s|\\.)?(\\d{3})$";   
        return str.matches(reg);
    }
    
    public void SuccessAnnouunce(String str) {// Hiện thị thông báo
        Icon icon = new javax.swing.ImageIcon(getClass().getResource("/image/success.png"));
        JOptionPane.showMessageDialog(null, str, "Success", JOptionPane.INFORMATION_MESSAGE, icon);
    }

    public void ErrorAnnounce(String str) {// Hiện thị thông báo
        Icon icon = new javax.swing.ImageIcon(getClass().getResource("/image/error.png"));
        JOptionPane.showMessageDialog(null, str, "Error", JOptionPane.INFORMATION_MESSAGE, icon);
    }

    public void WarningtAnnounce(String str) {// Hiện thị thông báo
        Icon icon = new javax.swing.ImageIcon(getClass().getResource("/image/warning.png"));
        JOptionPane.showMessageDialog(null, str, "Warning", JOptionPane.WARNING_MESSAGE, icon);
    }
    
    public void setBtnNoBorder(JToggleButton button)
    {
        button.setOpaque(false);
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        button.setContentAreaFilled(false);
        button.setBorder(BorderFactory.createEmptyBorder(0,0,0,0)); // Especially important
    }
    
    public void setBtnNoBorder(JButton button)
    {
        button.setOpaque(false);
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        button.setContentAreaFilled(false);
        button.setBorder(BorderFactory.createEmptyBorder(0,0,0,0)); // Especially important
    }
    
    
    public void setBtn()
    {
        setBtnNoBorder(btnDate);
        setBtnNoBorder(btnBack);
        setBtnNoBorder(btnRegister);
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnBack = new javax.swing.JToggleButton();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnRegister = new javax.swing.JToggleButton();
        rdFemale = new javax.swing.JRadioButton();
        rdMale = new javax.swing.JRadioButton();
        txtDate1 = new javax.swing.JTextField();
        btnDate = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(0, 20, 90, 70);

        txtName.setFont(new java.awt.Font("Calisto MT", 0, 26)); // NOI18N
        getContentPane().add(txtName);
        txtName.setBounds(260, 90, 400, 60);

        txtAddress.setFont(new java.awt.Font("Calisto MT", 0, 26)); // NOI18N
        getContentPane().add(txtAddress);
        txtAddress.setBounds(260, 360, 400, 60);

        txtTelephone.setFont(new java.awt.Font("Calisto MT", 0, 26)); // NOI18N
        txtTelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelephoneKeyPressed(evt);
            }
        });
        getContentPane().add(txtTelephone);
        txtTelephone.setBounds(260, 440, 400, 60);

        txtEmail.setFont(new java.awt.Font("Calisto MT", 0, 26)); // NOI18N
        getContentPane().add(txtEmail);
        txtEmail.setBounds(260, 530, 400, 60);

        btnRegister.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister);
        btnRegister.setBounds(390, 610, 140, 60);

        rdFemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdFemale);
        rdFemale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFemaleActionPerformed(evt);
            }
        });
        getContentPane().add(rdFemale);
        rdFemale.setBounds(500, 200, 20, 30);

        rdMale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdMale);
        rdMale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(rdMale);
        rdMale.setBounds(290, 200, 25, 30);

        txtDate1.setFont(new java.awt.Font("Calisto MT", 0, 26)); // NOI18N
        txtDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDate1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtDate1);
        txtDate1.setBounds(260, 270, 400, 60);

        btnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateActionPerformed(evt);
            }
        });
        getContentPane().add(btnDate);
        btnDate.setBounds(670, 280, 60, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/account_info.png"))); // NOI18N
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1210, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        RegisterView a = new RegisterView();
        a.setVisible(true);
        a.setTitle("Register");
        a.setLocationRelativeTo(null);
        a.setField(rg.getPerson().getUusername(), rg.getPerson().getUpassword());
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if(!checkBlankField())  
        {
            try {
                String name = txtName.getText();
                String gender = rdFemale.isSelected()?"Female":"Male";
                String address = txtAddress.getText();
                String telephone = txtTelephone.getText();
                String email = txtEmail.getText();
                String date1 = txtDate1.getText();
                Date date =new SimpleDateFormat("dd-MM-yyyy").parse(txtDate1.getText());
                if(checkPhone(telephone))
                {
                    if(checkEmailRegex(email))
                    {
                    rg.setInfo(name, gender,date, address, telephone, email);
                    rg.addPerson();
                    SuccessAnnouunce("Sucessfully");
                    this.dispose();
                    new LoginView();
                    }
                    else
                    {
                        txtEmail.setText("");
                    }
                }
                else
                {
                    WarningtAnnounce("Wrong format of phone number");
                    txtTelephone.setText("");
                }
            } catch (ParseException ex) {
                Logger.getLogger(AccounInformationView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            WarningtAnnounce("Must have complete all fields ");
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDate1ActionPerformed

    private void btnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateActionPerformed
        dateChooser.showPopup();
    }//GEN-LAST:event_btnDateActionPerformed

    private void rdFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFemaleActionPerformed

    private void txtTelephoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephoneKeyPressed
            String phoneNumber = txtTelephone.getText();
            int length = phoneNumber.length();
            if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')
            {
                if(length > 10)
                {
                    txtTelephone.setEditable(false);
                }
                else
                {
                    txtTelephone.setEditable(true);
                }
            }
            else
            {
                if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE)
                {
                    txtTelephone.setEditable(true);
                }
                else
                {
                    txtTelephone.setEditable(false);
                }
            }
    }//GEN-LAST:event_txtTelephoneKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccounInformationView().setVisible(true);
            }
        });
    }
      private com.raven.datechooser.DateChooser dateChooser;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JButton btnDate;
    private javax.swing.JToggleButton btnRegister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rdFemale;
    private javax.swing.JRadioButton rdMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDate1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
