package view;

import controller.AdminManagerCtl;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import model.Person;
import model.Topic;
import model.Word;
import static view.TopicManagerFrm.k;
import view.panel_adduser.panel_addUser;
import view.panel_editInfo.panel_editTopic;
import view.panel_editInfo.panel_editUser;
import view.panel_editInfo.panel_editWord;

/**
 *
 * @author Admin
 */
public class AdminManagerView extends javax.swing.JFrame {

    /**
     * Creates new form UserManagerView
     */
    public DefaultTableModel model;
    AdminManagerCtl a = new AdminManagerCtl();
    public static int k;
    panel_editUser pUser;

    public AdminManagerView() {
        initComponents();
        this.setSize(1214, 712);
        this.setTitle("Admin Mannager");
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/logoapp.png"));
        Image image = icon.getImage();
        setIconImage(image);
        setBtn();
    }

    public void setBtnNoBorder(JButton button) {
        button.setOpaque(false);
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        button.setContentAreaFilled(false);
        button.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0)); // Especially important
    }

    public void setBtnNoBorder(JToggleButton button) {
        button.setOpaque(false);
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        button.setContentAreaFilled(false);
        button.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0)); // Especially important
    }

    public void setBtn() {
        setBtnNoBorder(btnBack);
        setBtnNoBorder(btn_userMgr);
        setBtnNoBorder(btn_TopicMgr);
        setBtnNoBorder(btn_wordMgr);
        setBtnNoBorder(btn_viewRanking);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_userMgr = new javax.swing.JButton();
        btn_TopicMgr = new javax.swing.JButton();
        btn_viewRanking = new javax.swing.JButton();
        btn_wordMgr = new javax.swing.JButton();
        btnBack = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        btn_userMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userMgrActionPerformed(evt);
            }
        });
        getContentPane().add(btn_userMgr);
        btn_userMgr.setBounds(930, 150, 260, 250);

        btn_TopicMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TopicMgrActionPerformed(evt);
            }
        });
        getContentPane().add(btn_TopicMgr);
        btn_TopicMgr.setBounds(640, 430, 250, 240);

        btn_viewRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewRankingActionPerformed(evt);
            }
        });
        getContentPane().add(btn_viewRanking);
        btn_viewRanking.setBounds(930, 420, 250, 240);

        btn_wordMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_wordMgrActionPerformed(evt);
            }
        });
        getContentPane().add(btn_wordMgr);
        btn_wordMgr.setBounds(640, 150, 240, 250);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(1090, 0, 110, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/admin_screen.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1210, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_userMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userMgrActionPerformed
        this.dispose();
        new UserManagerView();
    }//GEN-LAST:event_btn_userMgrActionPerformed

    private void btn_TopicMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TopicMgrActionPerformed
        this.dispose();
        new TopicManagerFrm();
    }//GEN-LAST:event_btn_TopicMgrActionPerformed
    public void announcement(String str) {// Hiện thị thông báo
        JOptionPane.showMessageDialog(null, str);
    }
    private void btn_viewRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewRankingActionPerformed
        this.dispose();
        new StaticialView();
    }//GEN-LAST:event_btn_viewRankingActionPerformed

    private void btn_wordMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_wordMgrActionPerformed
        this.dispose();
        new WordManagerView();
    }//GEN-LAST:event_btn_wordMgrActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Icon icon = new javax.swing.ImageIcon(getClass().getResource("/image/warning.png"));
        int input = JOptionPane.showConfirmDialog(rootPane, "Do you want to exit", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, icon);
        if (input == 0) {
            this.dispose();
            new LoginView();
        }
//        this.dispose();
//        new HomeFrmAdmin();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminManagerView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JButton btn_TopicMgr;
    private javax.swing.JButton btn_userMgr;
    private javax.swing.JButton btn_viewRanking;
    private javax.swing.JButton btn_wordMgr;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
