/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ListCtl;
import controller.TopicCtl;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.Topic;
import model.Word;

/**
 *
 * @author Admin
 */
public class ListView extends javax.swing.JFrame {

    /**
     * Creates new form ListView
     */
    ListCtl listCtl = new ListCtl();
    ArrayList<Word> personWordList = new ArrayList<>();
    DefaultTableModel model;
    public ListView() {
        initComponents();
        this.setSize(1215, 730);// Kích thước Jframe
        this.setVisible(true); //Hiển thị
        this.setTitle("Your vocabulary");// Tiêu đề
        this.setLocationRelativeTo(null); // Hiển thị Jframe ở chính giữa màn hình
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/logoapp.png"));
        Image image = icon.getImage();
        setIconImage(image);
        tableVocabulary.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        setBtn();
        model = (DefaultTableModel) tableVocabulary.getModel();
        
        tableVocabulary.getTableHeader().setFont(new Font("DejaVu Sans", Font.PLAIN, 14));
        tableVocabulary.getTableHeader().setOpaque(false);
        tableVocabulary.getTableHeader().setBackground(new Color(32, 136, 203));
        tableVocabulary.getTableHeader().setForeground(new Color(255,255,255));
        
        showtable();
    }
    public void setBtnNoBorder(JButton button) {// Xóa viền button
        button.setOpaque(false);
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        button.setContentAreaFilled(false);
        button.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0)); // Especially important
    }

    public void setBtn() {// Xóa button Back, Remove
        setBtnNoBorder(btnBack);
        setBtnNoBorder(btnRemove);
    }
    
    public void SuccessAnnouunce(String str) {
        Icon icon = new javax.swing.ImageIcon(getClass().getResource("/image/success.png"));
        JOptionPane.showMessageDialog(null, str, "Success", JOptionPane.INFORMATION_MESSAGE, icon);
    }

    public void ErrorAnnounce(String str) {
        Icon icon = new javax.swing.ImageIcon(getClass().getResource("/image/error.png"));
        JOptionPane.showMessageDialog(null, str, "Error", JOptionPane.INFORMATION_MESSAGE, icon);
    }

    public void WarningtAnnounce(String str) {
        Icon icon = new javax.swing.ImageIcon(getClass().getResource("/image/warning.png"));
        JOptionPane.showMessageDialog(null, str, "Warning", JOptionPane.WARNING_MESSAGE, icon);
    }
    
    public void showtable()// Hiển thị danh sách từ vựng của user
    {
        personWordList = listCtl.getPersonWordList(TopicCtl.idperson);
        for(Word x: personWordList)
            {
                model.addRow(new Object[]{
                    x.getEn(), x.getVn()
                });
            }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableVocabulary = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tableVocabulary.setAutoCreateRowSorter(true);
        tableVocabulary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableVocabulary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "English", "Vietnamese"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVocabulary.setRowHeight(25);
        tableVocabulary.setShowVerticalLines(false);
        tableVocabulary.getTableHeader().setReorderingAllowed(false);
        tableVocabulary.setUpdateSelectionOnSort(false);
        tableVocabulary.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(tableVocabulary);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 130, 980, 440);

        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove);
        btnRemove.setBounds(520, 590, 210, 90);

        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(10, 30, 80, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/MY LIST.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1210, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
          int []indexs = tableVocabulary.getSelectedRows();
          if(indexs.length == 0)//Nếu không chọn dòng nào
          {
              WarningtAnnounce("Must be have select a word to remove");
          }
          else
          {
            for(int i = 0; i < indexs.length; i++)
            {
                String en = (String) tableVocabulary.getValueAt(indexs[i], 0);
                listCtl.removeWord(en);
            }
            model.setRowCount(0);
            showtable();
            if(listCtl.checkIDperson(TopicCtl.idperson))
            {
                SuccessAnnouunce("Sucessfully");
            }
            else
            {          
                WarningtAnnounce("Your vocabulary list is empty");
            }
         }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new HomeView();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVocabulary;
    // End of variables declaration//GEN-END:variables
}
