/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProfileCtl;
import controller.RegisterCtl;
import java.awt.Image;
import java.text.SimpleDateFormat;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import model.Person;

/**
 *
 * @author Admin
 */
public class ProfileView extends javax.swing.JFrame {

    /**
     * Creates new form AccounInformationFrm
     */

    public ProfileView() {
        initComponents();
        this.setSize(1215, 722);
        this.setTitle("Profile");
        this.setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/logoapp.png"));
        Image image = icon.getImage();
        setIconImage(image);
        setInformation();
        setBtn();
        this.setVisible(true);
    }
    
    public void setBtnNoBorder(JToggleButton button)
    {
        button.setOpaque(false);
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        button.setContentAreaFilled(false);
        button.setBorder(BorderFactory.createEmptyBorder(0,0,0,0)); // Especially important
    }
    
    public void setBtn()
    {
        setBtnNoBorder(btnBack);
        setBtnNoBorder(btnEditInformation);
        setBtnNoBorder(btnEditPassword);
    }
    
    public void setInformation()
    {
            ProfileCtl editCtl1 = new ProfileCtl();
            Person person = editCtl1.getPersonInformation();
            lbName.setText(person.getUname());
            lbGender.setText(person.getUgender());
            lbBirthday.setText(new SimpleDateFormat("dd-MM-yyyy").format(person.getUbirthday()));
            lbAddress.setText(person.getUaddress());
            lbPhone.setText(person.getUtelephone());
            lbEmail.setText(person.getUemail());

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnBack = new javax.swing.JToggleButton();
        btnEditInformation = new javax.swing.JToggleButton();
        btnEditPassword = new javax.swing.JToggleButton();
        lbBirthday = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        lbPhone = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(0, 20, 110, 110);

        btnEditInformation.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnEditInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditInformationActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditInformation);
        btnEditInformation.setBounds(220, 600, 340, 70);

        btnEditPassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditPassword);
        btnEditPassword.setBounds(640, 600, 350, 70);

        lbBirthday.setFont(new java.awt.Font("DejaVu Serif", 0, 30)); // NOI18N
        lbBirthday.setText("20-10-2001");
        getContentPane().add(lbBirthday);
        lbBirthday.setBounds(420, 270, 370, 50);

        lbEmail.setFont(new java.awt.Font("DejaVu Serif", 0, 30)); // NOI18N
        lbEmail.setText("vuhoaianh38@gmail.com");
        getContentPane().add(lbEmail);
        lbEmail.setBounds(420, 480, 470, 50);

        lbGender.setFont(new java.awt.Font("DejaVu Serif", 0, 30)); // NOI18N
        lbGender.setText("Female");
        getContentPane().add(lbGender);
        lbGender.setBounds(420, 200, 380, 40);

        lbName.setFont(new java.awt.Font("DejaVu Serif", 0, 30)); // NOI18N
        lbName.setText("Vu Hoai Anh");
        getContentPane().add(lbName);
        lbName.setBounds(420, 130, 530, 40);

        lbAddress.setFont(new java.awt.Font("DejaVu Serif", 0, 30)); // NOI18N
        lbAddress.setText("Hung Yen");
        getContentPane().add(lbAddress);
        lbAddress.setBounds(420, 340, 370, 50);

        lbPhone.setFont(new java.awt.Font("DejaVu Serif", 0, 30)); // NOI18N
        lbPhone.setText("0867405526");
        getContentPane().add(lbPhone);
        lbPhone.setBounds(420, 400, 370, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/my_profile.png"))); // NOI18N
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1210, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new HomeView();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditInformationActionPerformed
             this.dispose();
             new EditProfileView();
    }//GEN-LAST:event_btnEditInformationActionPerformed

    private void btnEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPasswordActionPerformed
        this.dispose();
        new ChangePasswordView();
    }//GEN-LAST:event_btnEditPasswordActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JToggleButton btnEditInformation;
    private javax.swing.JToggleButton btnEditPassword;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbBirthday;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPhone;
    // End of variables declaration//GEN-END:variables
}
